// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmFuWql8Su-fdpdKxiglSWeS1do4Wu15Q',
    appId: '1:733929455796:web:73c0849cb908f4fbdb17e1',
    messagingSenderId: '733929455796',
    projectId: 'memoeverywhere-b3cfb',
    authDomain: 'memoeverywhere-b3cfb.firebaseapp.com',
    storageBucket: 'memoeverywhere-b3cfb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_tUiZTXt9mmTMgA2YifU569NY6jZRt1c',
    appId: '1:733929455796:android:f4d43a446ed750dcdb17e1',
    messagingSenderId: '733929455796',
    projectId: 'memoeverywhere-b3cfb',
    storageBucket: 'memoeverywhere-b3cfb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCx06kgczABtLxV058RvaGkGWCU7m9PgRo',
    appId: '1:733929455796:ios:86881970a7b30bd4db17e1',
    messagingSenderId: '733929455796',
    projectId: 'memoeverywhere-b3cfb',
    storageBucket: 'memoeverywhere-b3cfb.firebasestorage.app',
    iosBundleId: 'kr.jm.memoEverywhere',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCx06kgczABtLxV058RvaGkGWCU7m9PgRo',
    appId: '1:733929455796:ios:86881970a7b30bd4db17e1',
    messagingSenderId: '733929455796',
    projectId: 'memoeverywhere-b3cfb',
    storageBucket: 'memoeverywhere-b3cfb.firebasestorage.app',
    iosBundleId: 'kr.jm.memoEverywhere',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmFuWql8Su-fdpdKxiglSWeS1do4Wu15Q',
    appId: '1:733929455796:web:ecfc28a434a72e0fdb17e1',
    messagingSenderId: '733929455796',
    projectId: 'memoeverywhere-b3cfb',
    authDomain: 'memoeverywhere-b3cfb.firebaseapp.com',
    storageBucket: 'memoeverywhere-b3cfb.firebasestorage.app',
  );
}
